name: energy-project-backend

on:
  push:
    # branches:
    #   - main
  # pull_request:
  #   branches:
  #     - dev
  #   types: [closed]

jobs:
  deploy-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        
      - name: rename env.example to .env
        run: mv .env.example .env

      - name: Run tests
        env:
          MONGO_URL: mongodb://localhost:27017/test_database
        run: npm run test


  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

        # Ensure that Prisma generates the client
      - name: Run Prisma Generate
        run: npx prisma generate
        env:
          DATABASE_URL: "mongodb+srv://admin:Ubuxa%23%2399@a4t.ldexs.mongodb.net/testdb?retryWrites=true&w=majority&appName=A4t"  # Make sure your database URL is provided in secrets
          # DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run build
        run: npm run build

      - name: Run build
        run: npm run build
      - name: Update apt repositories
        run: sudo apt update

      - name: rename env.example to .env
        run: mv .env.example .env

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: SSH login and deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync --delete -va -e 'ssh -p 7822 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no' \
            dist/ package.json node_modules .env skillz@103.72.76.68:energy/api